<?php

/**
 * @file
 * Contains dsu_c_image.module.
 */

/**
 * Implements hook_preprocess_HOOK() for paragraph.html.twig.
 */
function dsu_c_image_preprocess_paragraph__c_image(&$variables) {
  // Load the css file when the rendered element is a Image Paragraph.
  $variables['#attached']['library'][] = 'dsu_c_image/general';
}

/**
 * Implements hook_theme.
 */
function dsu_c_image_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__c_image' => [
      'template' => 'paragraph--c-image',
      'base hook' => 'paragraphs',
    ],
  ];
}

/**
 * Implements hook_ln_sample_content().
 */
function dsu_c_image_ln_sample_content() {
    /** @var \Drupal\Core\File\FileSystemInterface $file_system */
    $file_system = \Drupal::service('file_system');
    // Load the module extension.
    $extension = \Drupal::service('module_handler')->getModule('dsu_c_image');
    $files = $file_system->scanDirectory($extension->getPath() . DIRECTORY_SEPARATOR . 'content', '/demo.*\.(yml)$/');
    $yaml_file_path = NULL;
    foreach ($files as $file) {
        $yaml_file_path[] = '/content/' . $file->filename;
    }

    return $yaml_file_path;
}
