<?php

/**
 * @file
 * Install, update, and uninstall functions for the dsu_c_image module.
 */


/**
 * Refactor dsu_c_image module
 */
function dsu_c_image_update_9101() {
  \Drupal::service('dsu_core.config_replace')->rewriteModuleConfig('dsu_c_image');
}

function dsu_c_image_update_dependencies() {
  $dependencies['dsu_c_image'][9101] = [
    'dsu_c_core' => 9101,
  ];
  return $dependencies;
}
