<?php

/**
 * Implements HOOK_preprocess_theme().
 */
function dsu_c_slider_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__c_slide' => [
      'template' => 'paragraph--c-slide',
      'base hook' => 'paragraphs',
    ],
    'paragraph__c_slider' => [
      'template' => 'paragraph--c-slider',
      'base hook' => 'paragraphs',
    ],
  ];
}

/**
 * Implements hook_ln_sample_content().
 */
function dsu_c_slider_ln_sample_content() {
  /** @var \Drupal\Core\File\FileSystemInterface $file_system */
  $file_system = \Drupal::service('file_system');
  // Load the module extension.
  $extension = \Drupal::service('module_handler')->getModule('dsu_c_slider');
  $files = $file_system->scanDirectory($extension->getPath() . DIRECTORY_SEPARATOR . 'content', '/demo.*\.(yml)$/');
  $yaml_file_path = NULL;
  foreach ($files as $file) {
    $yaml_file_path[] = '/content/' . $file->filename;
  }

  return $yaml_file_path;
}

/**
 * Implements hook_preprocess_HOOK() for paragraph.html.twig.
 */
function dsu_c_slider_preprocess_paragraph__c_slider(&$variables) {
  // Load the library when the rendered element is a  dsu_c_slider Paragraph.
  $variables['#attached']['library'][] = 'dsu_c_slider/slider';
}
