dsu_article:
  id: "dsu_article"
  name: "Lightnest Article"
  description: "Provides Article content type and related configuration. Use articles to add timely content to your site.Please Note: Article Content Type is pre-selected as this is needed for generating installation report"
  default_checked: "1"
  disabled: TRUE
ln_adimo:
  id: "ln_adimo"
  name: "Lightnest Adimo Integration"
  description: "Lightnest Drupal module for Adimo services."
  default_checked: "0"
  disabled: FALSE
ln_bazaarvoice:
  id: "ln_bazaarvoice"
  name: "Lightnest Bazaarvoice"
  description: "Lightnest Provides integration with the Bazaarvoice Conversations API."
  default_checked: "0"
  disabled: FALSE
ln_contenthub:
  id: "ln_contenthub"
  name: "Lightnest Content Hub"
  description: "Add images easily from Content Hub."
  default_checked: "0"
  disabled: FALSE
dsu_engage:
  id: "dsu_engage"
  name: "Lightnest Engage"
  description: "Provide a Contact us form connected with Engage."
  default_checked: "0"
  disabled: FALSE
ln_contactus_block:
  id: "ln_contactus_block"
  name: "Lightnest Engage Contact Us Block"
  description: "Provides Engage Contact us form as a block."
  default_checked: "0"
  disabled: FALSE
ln_fusepump:
  id: "ln_fusepump"
  name: "Lightnest Fusepump Connector"
  description: "Adds the integration from Drupal to Fusepump."
  default_checked: "0"
  disabled: FALSE
dsu_product:
  id: "dsu_product"
  name: "Lightnest Product"
  description: "Provides Product content type and related configuration. A product for the site."
  default_checked: "0"
  disabled: FALSE
ln_c_power_reviews:
  id: "ln_c_power_reviews"
  name: "Lightnest PowerReviews connector"
  description: "Adds the integration from Drupal to PowerReviews API."
  default_checked: "0"
  disabled: FALSE
dsu_ratings_reviews:
  id: "dsu_ratings_reviews"
  name: "Lightnest Ratings and Reviews (New Version)"
  description: "Provides the ratings and review comment type."
  default_checked: "0"
  disabled: FALSE
ln_shopify:
  id: "ln_shopify"
  name: "Lightnest Shopify"
  description: "Connect with Shopify Buy Now Connector."
  default_checked: "0"
  disabled: FALSE
