<?php

  /**
   * @file
   * Implementing some hook function
   */
use Drupal\Core\Url;
use Drupal\Core\StringTranslation\TranslatableMarkup;
use Platformsh\ConfigReader\Config;
use Drupal\Core\Form\ConfigFormBase;
use Drupal\Core\Form\FormStateInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Drupal\user\Entity\User;
  function drupalup_cron_cron(){

    $curr_id_for_user = \Drupal::currentUser()->id();

    $config = new Config();

    $credentials = $config->credentials('database');

    $dsn = sprintf('mysql:host=%s;port=%d;dbname=%s', $credentials['host'], $credentials['port'], $credentials['path']);
    $conn = new \PDO($dsn, $credentials['username'], $credentials['password'], [
      \PDO::ATTR_ERRMODE => \PDO::ERRMODE_EXCEPTION,
      \PDO::MYSQL_ATTR_USE_BUFFERED_QUERY => TRUE,
      \PDO::MYSQL_ATTR_FOUND_ROWS => TRUE,
    ]);

    $roles = \Drupal::currentUser()->getRoles();


    $getTotalSQL = "SELECT COUNT(id) FROM promo_code WHERE active = '".$curr_id_for_user."'";
    $getTotal  = $conn->query($getTotalSQL);
    foreach ($getTotal as $total){}

    if($total['COUNT(id)'] % 15 ==0){
      $tombolaSuccess = "UPDATE promo_code SET tombola = 1, data = NOW() WHERE tombola = 0 ";
      if($conn->query($tombolaSuccess)){
        $getTombola = "SELECT * FROM promo_code WHERE tombola = 1";
        $tombolaZil  = $conn->query($getTombola);
        $tombolaZil->setFetchMode(\PDO::FETCH_OBJ);

        $ifUsers = 0;
        $arrID = array();
        foreach($tombolaZil as $zil){
          $ifUsers++;
          $arrID[] = $zil->active;
        }
        if($ifUsers >= 2){
          $key = array_rand($arrID);
        }
        echo 'random id user => '.$key;
      }
    }

    $tombolaSuccess = "UPDATE promo_code SET tombola = 99 WHERE id = 30";
    if($conn->query($tombolaSuccess)){}
  }
?>
