<?php

  /**
   * @file
   * Implementing some hook function
   */
use Drupal\Core\Url;
use Drupal\Core\StringTranslation\TranslatableMarkup;
use Platformsh\ConfigReader\Config;
use Drupal\Core\Form\ConfigFormBase;
use Drupal\Core\Form\FormStateInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Drupal\user\Entity\User;
  function drupalup_cron_cron(){

    $curr_id_for_user = \Drupal::currentUser()->id();

    $config = new Config();

    $credentials = $config->credentials('database');

    $dsn = sprintf('mysql:host=%s;port=%d;dbname=%s', $credentials['host'], $credentials['port'], $credentials['path']);
    $conn = new \PDO($dsn, $credentials['username'], $credentials['password'], [
      \PDO::ATTR_ERRMODE => \PDO::ERRMODE_EXCEPTION,
      \PDO::MYSQL_ATTR_USE_BUFFERED_QUERY => TRUE,
      \PDO::MYSQL_ATTR_FOUND_ROWS => TRUE,
    ]);
        $getTombola = "SELECT * FROM promo_code WHERE tombola = 1";
        $tombolaZil  = $conn->query($getTombola);
        $tombolaZil->setFetchMode(\PDO::FETCH_OBJ);

        $ifUsers = 0;
        $arrID = array();
        foreach($tombolaZil as $zil){
          $ifUsers++;
          $arrID[] = $zil->id;
        }
        if($ifUsers >= 2){
          $key = array_rand($arrID);
        }

    $tombolaSuccess = "UPDATE promo_code SET tombola = 2 WHERE id = '".$arrID[$key]."'";
    if($conn->query($tombolaSuccess)){}

    $getFinal = "SELECT * FROM promo_code WHERE final = 1";
    $finalZil  = $conn->query($getFinal);
    $finalZil->setFetchMode(\PDO::FETCH_OBJ);

    $ifUsers = 0;
    $arrID = array();
    foreach($finalZil as $zil){
      $ifUsers++;
      $arrID[] = $zil->id;
    }
    if($ifUsers >= 2){
      $key = array_rand($arrID);
    }

    $FinalSuccess = "UPDATE promo_code SET final = 2 WHERE id = '".$arrID[$key]."'";
    if($conn->query($FinalSuccess)){}

  }
?>
