notification_system_dispatch_webpush.settings:
  type: mapping
  label: 'Notification System Dispatch Web Push settings'
  mapping:
    langcode:
      type: string
      label: 'Default language'
    subject_template:
      type: text
      label: 'Subject'
    body_template:
      type: text
      label: 'Body'
    body_max_length:
      type: integer
      label: 'Body max length'
    vapid_public_key:
      type: string
      label: 'VAPID Public Key'
    vapid_private_key:
      type: string
      label: 'VAPID Private Key'
    icon_path:
      type: string
      label: 'Path to website icon'
    badge_path:
      type: string
      label: 'Path to badge icon'
    apple_enabled:
      type: boolean
      label: 'Indicates if MacOS push support is enabled'
    apple_cert_path:
      type: string
      label: 'Path to the apple certificate file'
    apple_cert_password:
      type: string
      label: 'Password for the apple certificate file'
    apple_website_push_id:
      type: string
      label: 'Apple Website push ID'
