block.settings.notification_system_dispatch_webpush_popup:
  type: block_settings
  label: 'Webpush Popup block'
  mapping:
    info_value:
      type: label
      label: 'Content'
    info_format:
      type: string
      label: 'Content Format'
    button_enable:
      type: label
      label: 'Button: Enable'
    button_later:
      type: label
      label: 'Button: Ask later'
    button_cancel:
      type: label
      label: "Button: Don't ask again"
    ask_later_days:
      type: integer
      label: 'How many days to wait when user clicks later'

