# Schema for the configuration files of No Referrer module.

noreferrer.settings:
  type: config_object
  label: 'No Referrer settings'
  mapping:
    noopener:
      type: boolean
      label: 'Add rel="noopener" if link has a target'
    noreferrer:
      type: boolean
      label: 'Add rel="noreferrer" to non-allowed links'
    publish:
      type: boolean
      label: 'Publish list of allowed domains'
    subscribe_url:
      type: string
      label: 'Subscribe to external list of allowed domains'
    allowed_domains:
      type: string
      label: 'Allowed domains'
