<?php

/**
 * @file
 * Contains ln_bazaarvoice.module file.
 */

use \Drupal\ln_bazaarvoice\LnBazaarvoiceConstants;
use \Drupal\Core\Entity\EntityInterface;
use \Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements hook_theme().
 */
function ln_bazaarvoice_theme($existing, $type, $theme, $path) {
  return [
    'ln_bazaarvoice' => [
      'variables' => [
        'mode' => LnBazaarvoiceConstants::MODE_REVIEWS,
        'bazaarvoice_id' => NULL,
        'bazaarvoice_entity' => NULL,
        'seo' => TRUE,
        'dcc_info' => ''
      ],
    ],
    'ln_bazaarvoice__rating_summary' => [
      'base hook' => 'ln_bazaarvoice',
    ],
    'ln_bazaarvoice__reviews' => [
      'base hook' => 'ln_bazaarvoice',
    ],
    'ln_bazaarvoice__questions' => [
      'base hook' => 'ln_bazaarvoice',
    ],
    'ln_bazaarvoice__review_highlights' => [
      'base hook' => 'ln_bazaarvoice',
    ],
    'ln_bazaarvoice__inline_rating' => [
      'base hook' => 'ln_bazaarvoice',
    ],
    'ln_bazaarvoice__seller_ratings' => [
      'base hook' => 'ln_bazaarvoice',
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function ln_bazaarvoice_theme_suggestions_ln_bazaarvoice(array $variables) {
  return ["ln_bazaarvoice__{$variables['mode']}"];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function ln_bazaarvoice_preprocess_ln_bazaarvoice(&$variables) {
  /** @var \Drupal\ln_bazaarvoice\Service\LnBazaarvoiceServiceInterface $bazaarvoice_utils */
  $bazaarvoice_utils = \Drupal::service('ln_bazaarvoice.utils');
  $variables['#attached']['library'][] = 'ln_bazaarvoice/embed';
  $settings['js_url'] = $bazaarvoice_utils->getBazaarvoiceJsPath();
  if(($entity = $variables['bazaarvoice_entity']) && ($dcc_info = $variables['dcc_info'])){
    $settings['products'] = [
      $entity->id() => $bazaarvoice_utils->getProductInfo($variables['bazaarvoice_id'], $entity, $dcc_info)
    ];
  }
  $variables['#attached']['drupalSettings']['ln_bazaarvoice'] = $settings;
}

/**
 * Implements hook_entity_extra_field_info().
 */
function ln_bazaarvoice_entity_extra_field_info() {
  $extra = [];

  foreach(\Drupal::service('entity_field.manager')->getFieldMapByFieldType('ln_bazaarvoice_id') as $entity_type => $fields){
    foreach ($fields as $field_name => $field){
      foreach ($field['bundles'] as $bundle){
        $extra[$entity_type][$bundle]['display']['bazaarvoice_summary'] = [
          'label' => t('Bazaarvoice summary'),
          'description' => t('Bazaarvoice summary to use alongside reviews in full view mode'),
          'weight' => 100,
        ];
      }
    }
  }

  return $extra;
}

/**
 * Implements hook_entity_view().
 */
function ln_bazaarvoice_entity_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($display->getComponent('bazaarvoice_summary')) {
    foreach ($entity->getFieldDefinitions() as $field_name => $field){
      if($field->getType() == 'ln_bazaarvoice_id'){
        $build['bazaarvoice_summary'] = [
          '#theme' => "ln_bazaarvoice",
          '#mode' => LnBazaarvoiceConstants::MODE_RATING_SUMMARY,
          '#bazaarvoice_id' => $entity->get($field_name)->value,
          '#seo' => FALSE,
        ];
      }
    }
  }
}
