metatag.metatag_tag.srh_ins_image:
  type: label
  label: 'SRH Instagram Image'
metatag.metatag_tag.srh_ins_title:
  type: label
  label: 'SRH Instagram Title'
metatag.metatag_tag.srh_ins_description:
  type: label
  label: 'SRH Instagram Description'
metatag.metatag_tag.srh_alternate:
  type: label
  label: 'SRH Alternate'
