<?php

/**
 * Implements hook_theme().
 */
function ln_ciamlite_theme($existing, $type, $theme, $path) {
  return [
    'ln_ciamlite_gigya_newletter_block'    => [
      'variables' => [
        'title' => NULL,
        'subtitle' => NULL,
        'gigya_screen' => NULL,
      ],
    ],
    'ln_ciamlite_gigya_screen_block'    => [
      'variables' => [
        'screen_id' => NULL,
        'element_id' => NULL,
      ],
    ],
  ];
}

