<?php

use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Access\AccessResult;
use Drupal\ln_campaign\LnCWebformSubmissionListBuilder;


function ln_campaign_theme() {
  return [
    'ln_campaign_edit_form' => [
      'render element' => 'form',
    ],
    'ln_campaign_authentication_link' => [
      'variables' => [
        'title' => '',
        'url' => '',
        'message' => '',
      ],
      'template' => 'ln-campaign-authentication-link'
    ],
    'ln_campaign_time_out' => [
      'variables' => [
        'title' => '',
        'message' => '',
      ],
      'template' => 'ln-campaign-time-out'
    ]
  ];
}


function ln_campaign_webform_element_access($operation, array &$element, AccountInterface $account = NULL, array $context = []) {
  $accessProperty = '#access_' . $operation . '_workflow_enabled';
  if (isset($element['#workflow'])) {
    if (!isset($element[$accessProperty])) {
      if ($operation == 'create') {
        return AccessResult::forbidden();
      }
      return AccessResult::neutral();
    }
    if (!$element[$accessProperty]) {
      return AccessResult::forbidden();
    }
  }

  return AccessResult::neutral();
}


  /**
   * Add list builder class to make filterable by state
   *
   * @param array $entity_types
   */
  function ln_campaign_entity_type_alter(array &$entity_types) {
    $entity_types['webform_submission']->setHandlerClass('list_builder', LnCWebformSubmissionListBuilder::class);
  }

