id: noreferrer_settings
label: No Referrer settings
migration_tags:
  - Drupal 7
  - Configuration
source:
  plugin: variable
  variables:
    - noreferrer_noopener
    - noreferrer_noreferrer
    - noreferrer_publish
    - noreferrer_subscribe_url
    - noreferrer_allowed_domains
  source_module: noreferrer
process:
  noopener: noreferrer_noopener
  noreferrer: noreferrer_noreferrer
  publish: noreferrer_publish
  subscribe_url: noreferrer_subscribe_url
  allowed_domains: noreferrer_allowed_domains
destination:
  plugin: config
  config_name: noreferrer.settings
