dsu_c_core.classy_group.*:
  type: config_entity
  label: 'Classy group config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    multiple:
      type: boolean
      label: 'multiple'
    bundles:
      type: 'sequence'
      label: 'Bundles'
      sequence:
        type: paragraphs.paragraphs_type
    classys:
      type: sequence
      label: 'Classys'
      sequence:
        type: classy_paragraphs.classy_paragraphs_style
