<?php

/**
 * @file
 * Contains dsu_c_sideimagetext.module.
 */


/**
 * Implements hook_preprocess_HOOK() for paragraph.html.twig.
 */
function dsu_c_sideimagetext_preprocess_paragraph__c_sideimagetext(&$variables) {
  $variables['#attached']['library'][] = 'dsu_c_sideimagetext/general';
}

/**
 * Implements hook_theme.
 */
function dsu_c_sideimagetext_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__c_sideimagetext' => [
      'template' => 'paragraph--c-sideimagetext',
      'base hook' => 'paragraphs',
    ],
  ];
}

/**
 * Implements hook_ln_sample_content().
 */
function dsu_c_sideimagetext_ln_sample_content() {
  /** @var \Drupal\Core\File\FileSystemInterface $file_system */
  $file_system = \Drupal::service('file_system');
  // Load the module extension.
  $extension = \Drupal::service('module_handler')->getModule('dsu_c_sideimagetext');
  $files = $file_system->scanDirectory($extension->getPath() . DIRECTORY_SEPARATOR . 'content', '/demo.*\.(yml)$/');
  $yaml_file_path = NULL;
  foreach ($files as $file) {
    $yaml_file_path[] = '/content/' . $file->filename;
  }

  return $yaml_file_path;
}
