<?php

/**
 * @file
 * Install, update, and uninstall functions for the dsu_c_sideimagetext module.
 */


/**
 * Refactor dsu_c_sideimagetext module
 */
function dsu_c_sideimagetext_update_9101() {
  \Drupal::service('dsu_core.config_replace')->rewriteModuleConfig('dsu_c_sideimagetext');
}

function dsu_c_sideimagetext_update_dependencies() {
  $dependencies['dsu_c_sideimagetext'][9101] = [
    'dsu_c_core' => 9101,
  ];
  return $dependencies;
}
