<?php

/**
 * @file
 * Install, update, and uninstall functions for the dsu_c_text module.
 */


/**
 * Implements hook_update().
 * DWDL-3197 : Refactor Text component.
 * Refactor dsu_c_text module
 */
function dsu_c_text_update_9101() {
  \Drupal::service('dsu_core.config_replace')->rewriteModuleConfig('dsu_c_text');
}

function dsu_c_text_update_dependencies() {
  $dependencies['dsu_c_text'][9101] = [
    'dsu_c_core' => 9101,
  ];
  return $dependencies;
}
