<?php

/**
 * @file
 */

use Drupal\field\FieldConfigInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements HOOK_preprocess_theme().
 */
function ln_c_newsletter_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__c_newsletter_signup_cta' => [
      'template'  => 'paragraph--c-newsletter-signup-cta',
      'base hook' => 'paragraphs',
    ],
    'webform__newsletter_email_collection' => [
      'base hook' => 'webform',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK() for paragraph.html.twig.
 */
function ln_c_newsletter_preprocess_paragraph(&$variables) {
  if ($variables['paragraph']->getType() == 'c_newsletter_signup_cta') {

    $info = \Drupal::service('extension.list.module')->getExtensionInfo('ln_c_newsletter');

    $variables['#attached']['library'][] = 'ln_c_newsletter/ln_c_newsletter';
    $variables['#attached']['drupalSettings']['ln_c_newsletter']['data'] = [
      'module_name' => $info['name'],
      'module_version' => $info['version'],
    ];
  }
}

/**
 * Implements hook_form_alter().
 *
 * Add submit handler on contactus webform.
 */
function ln_c_newsletter_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (strstr($form_id, 'webform_submission_newsletter_email_collection_')) {
	  $form['#attached']['library'][] = 'ln_c_newsletter/webform-styling';
    $info = \Drupal::service('extension.list.module')->getExtensionInfo('ln_c_newsletter');

    $form['#validate'][] = 'ln_c_newsletter_validate';
    $form['#attached']['drupalSettings']['ln_c_newsletter']['data'] = [
      'form_id' => $form_id,
      'form_type' => 'webform',
      'module_name' => $info['name'],
      'module_version' => $info['version'],
    ];
  }
}

function ln_c_newsletter_validate(array &$form, FormStateInterface $form_state) {
  if ($form_state->getErrors()) {
    $form['ln_c_newsletter_error'] = [
      '#type' => 'markup',
      '#prefix' => '<div class ="ln-c-newsletter-error">',
      '#suffix' => '</div>',
    ];
  }
}
