ln_bazaarvoice.settings:
  type: mapping
  label: 'LN Bazaarvoice Settings'
  mapping:
    environment:
      type: string
      label: 'Environment'
    client_name:
      type: string
      label: 'Client Name'
    site_id:
      type: string
      label: 'Site Id'
