language: php
dist: xenial

php:
  - 7.2

services:
  - mysql

cache:
  apt: true
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"
    - "$HOME/.npm"

branches:
  only:
    - /^8\.([0-9]+|x)\-[0-9]+\.([0-9]+|x)$/

env:
  global:
    - PATH="$PATH:$HOME/.composer/vendor/bin:$HOME/.config/composer/vendor/bin"
    - DRUPAL_TRAVIS_TEST_CODING_STYLES=false
    - DRUPAL_TRAVIS_VERBOSE=true
    - DRUPAL_TRAVIS_COMPOSER_PROJECT="drupal/recommended-project=8.*"

before_install:
  # @todo `thunder/travis` doesn't work with composer 2.x. https://github.com/thunder/travis/issues/58
  - composer self-update --1
  - composer global require thunder/travis

script:
  - test-drupal-project
