<?php

/**
 * @file
 * Web Push API.
 */

use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Utility\Error;
use Drupal\web_push_api\Entity\WebPushSubscriptionInterface;

/**
 * Implements hook_ENTITY_TYPE_delete().
 *
 * @internal
 */
function web_push_api_user_delete(AccountInterface $account): void {
  try {
    Drupal::entityTypeManager()->getStorage(WebPushSubscriptionInterface::ENTITY_TYPE)->deleteByUserAccount($account);
  }
  catch (Exception $e) {
    Drupal::logger(__FUNCTION__)->error(Error::renderExceptionSafe($e));
  }
}
