<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Url;
use Drupal\ln_srh\SRHConstants;
use Drupal\ln_srh\Form\SRHConnectionSettings;

/**
 * Implements hook_theme().
 */
function ln_srh_full_theme($existing, $type, $theme, $path) {
  return [
    'srh_ingredients_full' => [
      'variables' => [
        'elements' => [],
        'show_change_display' => FALSE,
        'show_portion_spinner' => FALSE,
        'serving' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_cron().
 */
function ln_srh_full_cron() {
  $srh_connection_settings = \Drupal::config(SRHConnectionSettings::SETTINGS);
  if ($srh_connection_settings->get('enable_complements_sync')) {
    $current_time = \Drupal::time()->getRequestTime();
    $timeSync = \Drupal::state()->get('ln_srh_complements_last_sync', 0);
    $next_execution_time = $timeSync + $srh_connection_settings->get('interval_time');
    if ($current_time > $next_execution_time) {
      /** @var \Drupal\ln_srh_full\Services\SRHComplementUtilsInterface $srh_utils */
      $srh_utils = \Drupal::service('ln_srh_full.complement_utils');
      $srh_utils->syncComplements();
      \Drupal::state()->set('ln_srh_complements_last_sync', $current_time);
    }
  }
}

/**
 * Implements hook_entity_operation_alter().
 */
function ln_srh_full_entity_operation_alter(array &$operations, EntityInterface $entity) {
  if ($entity->getEntityTypeId() == 'node' && $entity->bundle() == SRHConstants::SRH_COMPLEMENT_BUNDLE) {
    $operations['srh_sync_complement'] = [
      'title' => t('SRH Sync'),
      'weight' => 110,
      'url' => Url::fromRoute('ln_srh_full.sync_node_complement', ['node' => $entity->id()]),
    ];
  }
}

/**
 * Prepares variables for srh_ingredients_full templates.
 *
 * Default template: srh-ingredients-full.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: The ingredients array elements.
 *   - show_change_display: A boolean indicating if the change display widget is active or not
 *   - show_portion_spinner: A boolean indicating if the portion spinner widget is active or not
 */
function template_preprocess_srh_ingredients_full(&$variables) {
  if ($variables['show_change_display']) {
    $variables['#attached']['library'][] = 'ln_srh_full/change_display';
  }
  if ($variables['show_portion_spinner']) {
    $variables['#attached']['library'][] = 'ln_srh_full/portion_spinner';
  }
}

/**
 * Preprocess srh_lets_cook_it flag to attach js library.
 */
function ln_srh_full_preprocess_flag__srh_lets_cook_it(&$variables) {
  $variables['#attached']['library'][] = 'ln_srh_full/lets_cook_it';
  $variables['attributes']['class'][] = 'btn';
}
