<?php

/**
 * @file
 * Contains newnestlegermany_components_accordion.module.
 */

use Drupal\paragraphs\Entity\Paragraph;
/**
 * Implements hook_theme().
 */
function dsu_c_accordion_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__accordion' => [
      'template' => 'paragraph--accordion',
      'base hook' => 'paragraph',
    ],
    'paragraph__accordion_item' => [
      'template' => 'paragraph--accordion-item',
      'base hook' => 'paragraph',
    ],
  ];
}

/**
 * Implements hook_ln_sample_content().
 */

function dsu_c_accordion_ln_sample_content() {
  /** @var \Drupal\Core\File\FileSystemInterface $file_system */
  $file_system = \Drupal::service('file_system');
  // Load the module extension.
  $extension = \Drupal::service('module_handler')->getModule('dsu_c_accordion');
  $files = $file_system->scanDirectory($extension->getPath() . DIRECTORY_SEPARATOR . 'content', '/demo.*\.(yml)$/');
  $yaml_file_path = NULL;
  foreach ($files as $file) {
    $yaml_file_path[] = '/content/' . $file->filename;
  }

  return $yaml_file_path;
}

/**
 * Implements hook_preprocess_HOOK() for paragraph.html.twig.
 */
function dsu_c_accordion_preprocess_paragraph__accordion(&$variables) {
  // Load the library when the rendered element is a  dsu_c_accordion Paragraph.
  $variables['#attached']['library'][] = 'dsu_c_accordion/accordion';
}
