action.configuration.ln_campaign_submission_invalidate_action:
  type: action_configuration_default
  label: 'Change to Invalidate status configuration'
action.configuration.ln_campaign_submission_validate_action:
  type: action_configuration_default
  label: 'Change to Validate status configuration'
action.configuration.ln_campaign_submission_pending_action:
  type: action_configuration_default
  label: 'Change to Pending status configuration'
action.configuration.ln_campaign_submission_paid_action:
  type: action_configuration_default
  label: 'Change to Paid status configuration'
