workflow.type_settings.ln_campaign_workflows_element:
  type: mapping
  label: 'Campaign workflow'
  mapping:
    initial_state:
      type: string
      label: 'Initial state'
    states:
      type: sequence
      sequence:
        type: workflows.state
    transitions:
      type: sequence
      sequence:
        type: workflows.transition
